modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="countrycraft"
version="1.0.0"
displayName="Country Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="NorthWestTrees Gaming, MCreator"

[[dependencies.countrycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



